@OperatorV2 @MiddleMile @Hub @InterHub @ShipmentManagement @EditShipment3
Feature: Shipment Management - Edit Shipment 3

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteShipment
  Scenario: Re-open Shipment - Invalid Shipment Status - Pending (uid:5ddf5f14-3298-4e4e-a747-aa832bb234bd)
    When Operator go to menu Inter-Hub -> Shipment Management
    And API Operator create new shipment with type "AIR_HAUL" from hub id = {hub-id} to hub id = {hub-id-2}
    And Operator search shipments by given Ids on Shipment Management page:
      | {KEY_LIST_OF_CREATED_SHIPMENT_ID[1]} |
    When Operator clicks on reopen shipment button under the Apply Action
    Then Operator verifies that the Reopen Shipment Button is disabled

  @DeleteShipment
  Scenario: Re-open Shipment - Invalid Shipment Status - Transit (uid:f8ccf5c9-85be-420a-b870-54bd4868b793)
    Given Operator go to menu Utilities -> QRCode Printing
    When Operator go to menu Inter-Hub -> Shipment Management
    Given API Shipper create V4 order using data below:
      | generateFromAndTo | RANDOM                                                                                                                                                                                                                                                                                                                           |
      | v4OrderRequest    | { "service_type":"Parcel", "service_level":"Standard", "parcel_job":{ "is_pickup_required":false, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    Given API Operator Global Inbound parcel using data below:
      | globalInboundRequest | { "hubId":{hub-id} } |
    And API Operator create new shipment with type "AIR_HAUL" from hub id = {hub-id} to hub id = {hub-id-2}
    When API Operator adds parcels to shipment using following data:
      | country    | sg                              |
      | trackingId | {KEY_CREATED_ORDER_TRACKING_ID} |
      | actionType | ADD                             |
    And API Operator closes the created shipment
    And API Operator performs van inbound by updating shipment status using data below:
      | scanValue  | {KEY_CREATED_SHIPMENT_ID} |
      | hubCountry | SG                        |
      | hubId      | {hub-id}                  |
    And Operator search shipments by given Ids on Shipment Management page:
      | {KEY_LIST_OF_CREATED_SHIPMENT_ID[1]} |
    And Operator verify the following parameters of all created shipments on Shipment Management page:
      | status | Transit|
    When Operator clicks on reopen shipment button under the Apply Action
    Then Operator verifies that the Reopen Shipment Button is disabled

  @DeleteHubsViaDb @DeleteCreatedShipments @DeleteMiddleMileDriver @ForceCompleteCreatedMovementTrips
  Scenario: Re-open Shipment - Invalid Shipment Status - Completed (uid:dabe7158-2e9d-4a69-a35d-8b66ff5872b0)
    Given Operator go to menu Utilities -> QRCode Printing
    When Operator go to menu Inter-Hub -> Shipment Management
    When API Operator creates 2 new Hub using data below:
      | name         | GENERATED |
      | displayName  | GENERATED |
      | facilityType | CROSSDOCK |
      | city         | GENERATED |
      | country      | GENERATED |
      | latitude     | GENERATED |
      | longitude    | GENERATED |
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Operator creates ad hoc trip
      | requestBody | {"origin_hub_id":"{KEY_LIST_OF_CREATED_HUBS[1].id}","origin_hub_system_id":"sg","destination_hub_id":"{KEY_LIST_OF_CREATED_HUBS[2].id}","destination_hub_system_id":"sg","departure_datetime":"{date: 0 seconds next, yyyy-MM-dd}T23:00:00Z","duration_time":"00:00:30","movement_type":"LAND_HAUL"} |
    When API MM - Operator assigns driver to movement trip with data below:
      | driver       | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
      | priority     | primary                                       |
      | movementTrip | KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]      |
    When API MM - Operator creates multiple 1 new shipments with type "LAND_HAUL" from hub id "{KEY_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_LIST_OF_CREATED_HUBS[2].id}"
    When API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
    When API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanType    | SHIPMENT_VAN_INBOUND                    |
      | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}  |
      | actionType  | ADD                                     |
    When API MM - Operator end shipment inbound with movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanType | SHIPMENT_VAN_INBOUND |
      | driverId | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id} |
    When API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator gets shipment details with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}"
    And API MM - Operator verifies events below for shipment "KEY_MM_LIST_OF_CREATED_SHIPMENTS[1]" exist:
      | SHIPMENT_VAN_INBOUND | Transit |
    When API MM - Operator "arrive" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanType    | SHIPMENT_HUB_INBOUND                    |
      | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}  |
      | actionType  | ADD                                     |
    When API MM - Operator "complete" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When API MM - Operator end shipment inbound with movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanType | SHIPMENT_HUB_INBOUND |
      | driverId | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id} |
    And Operator search shipments by given Ids on Shipment Management page:
      | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
    Then Operator verify parameters of shipment on Shipment Management page:
      | id     | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
      | status | Completed                 |
    When Operator clicks on reopen shipment button under the Apply Action
    Then Operator verifies that the Reopen Shipment Button is disabled

  @HappyPath @DeleteShipment @CloseNewWindows
  Scenario: Upload Bulk Orders to Shipment with Valid Tracking ID Data (uid:db962525-cadb-4314-8e90-1a5d7bb3a3a4)
    Given Operator go to menu Utilities -> QRCode Printing
    When Operator go to menu Inter-Hub -> Shipment Management
#    Given Operator go to menu Inter-Hub -> Shipment Management
    And API Operator create new shipment with type "AIR_HAUL" from hub id = {hub-id} to hub id = {hub-id-2}
    Given API Shipper create multiple V4 orders using data below:
      | numberOfOrder     | 3                                                                                                                                                                                                                                                                                                                                |
      | generateFromAndTo | RANDOM                                                                                                                                                                                                                                                                                                                           |
      | v4OrderRequest    | { "service_type":"Parcel", "service_level":"Standard", "parcel_job":{ "is_pickup_required":false, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    And Operator search shipments by given Ids on Shipment Management page:
      | {KEY_LIST_OF_CREATED_SHIPMENT_ID[1]} |
    When Operator create CSV "{csv-upload-file-name}" file which has multiple valid Tracking ID in it and upload the CSV
    And Operator open the shipment detail for the created shipment on Shipment Management Page
    Then Operator verify the Shipment Details Page opened is for the created shipment

  @DeleteShipment @CloseNewWindows
  Scenario: Upload Bulk Orders to Shipment with Duplicate Tracking ID Data (uid:76ff878a-2998-4656-a9de-62af667591d9)
    Given Operator go to menu Utilities -> QRCode Printing
    When Operator go to menu Inter-Hub -> Shipment Management
#    Given Operator go to menu Inter-Hub -> Shipment Management
    And API Operator create new shipment with type "AIR_HAUL" from hub id = {hub-id} to hub id = {hub-id-2}
    Given API Shipper create multiple V4 orders using data below:
      | numberOfOrder     | 3                                                                                                                                                                                                                                                                                                                                |
      | generateFromAndTo | RANDOM                                                                                                                                                                                                                                                                                                                           |
      | v4OrderRequest    | { "service_type":"Parcel", "service_level":"Standard", "parcel_job":{ "is_pickup_required":false, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    And Operator search shipments by given Ids on Shipment Management page:
      | {KEY_LIST_OF_CREATED_SHIPMENT_ID[1]} |
    When Operator create CSV "{csv-upload-file-name}" file which has duplicated Tracking ID in it and upload the CSV
    And Operator open the shipment detail for the created shipment on Shipment Management Page
    Then Operator verify the Shipment Details Page opened is for the created shipment

  @HappyPath @DeleteShipment
  Scenario: Upload Bulk Orders to Shipment with Invalid Tracking ID Data (uid:06c9f41b-780b-40f3-8c34-d422ded305f6)
    Given Operator go to menu Utilities -> QRCode Printing
    When Operator go to menu Inter-Hub -> Shipment Management
#    Given Operator go to menu Inter-Hub -> Shipment Management
    And API Operator create new shipment with type "AIR_HAUL" from hub id = {hub-id} to hub id = {hub-id-2}
    And Operator search shipments by given Ids on Shipment Management page:
      | {KEY_LIST_OF_CREATED_SHIPMENT_ID[1]} |
    When Operator create CSV "{csv-upload-file-name}" file which has invalid Tracking ID in it and upload the CSV

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op