@OperatorV2 @MiddleMile @Hub @InterHub @ShipmentManagement @ShipmentEvents
Feature: Shipment Management - Shipment Events

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
	Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteCreatedShipments
  Scenario: Shipment Events - Create Shipment
	When API MM - Operator creates multiple 1 new shipments with type "LAND_HAUL" from hub id "{hub-id}" to "{hub-id-2}"
	Given Operator go to menu Shipper Support -> Blocked Dates
	When Operator go to menu Inter-Hub -> Shipment Management
	And Operator search shipments by given Ids on Shipment Management page:
	  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	And Operator open the shipment detail for the shipment "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" on Shipment Management Page
	When API MM - Operator verifies shipment with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" has events below:
	  | SHIPMENT_CREATED | Pending |

  @DeleteCreatedShipments @DeleteMiddleMileDriver @DeleteCreatedMovementSchedules
  Scenario: Shipment Events - Close Shipment
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 months next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 months next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When API MM - Create "LAND_HAUL" Movement Schedule from "{hub-id}" to "{hub-id-2}" with data below:
	  | startTime | {date: 20 minutes next, yyyy-MM-dd HH:mm:ss}  |
	  | duration  | 00:00:10                                      |
	  | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
	When API MM - Operator creates multiple 1 new shipments with type "LAND_HAUL" from hub id "{hub-id}" to "{hub-id-2}"
	When API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
	Given Operator go to menu Shipper Support -> Blocked Dates
	When Operator go to menu Inter-Hub -> Shipment Management
	And Operator search shipments by given Ids on Shipment Management page:
	  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	And Operator open the shipment detail for the shipment "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" on Shipment Management Page
	When API MM - Operator verifies shipment with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" has events below:
	  | SHIPMENT_CREATED | Pending |
	  | SHIPMENT_CLOSED  | Closed  |

  @DeleteCreatedShipments @CloseNewWindows
  Scenario: Shipment Events - Re-open Shipment
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 months next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 months next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When API MM - Create "LAND_HAUL" Movement Schedule from "{hub-id}" to "{hub-id-2}" with data below:
	  | startTime | {date: 20 minutes next, yyyy-MM-dd HH:mm:ss}  |
	  | duration  | 00:00:10                                      |
	  | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
	When API MM - Operator creates multiple 1 new shipments with type "LAND_HAUL" from hub id "{hub-id}" to "{hub-id-2}"
	When API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
	And API Operator opens "{KEY_MM_LIST_OF_CREATED_SHIPMENTS}" shipment
	Given Operator go to menu Shipper Support -> Blocked Dates
	When Operator go to menu Inter-Hub -> Shipment Management
	And Operator search shipments by given Ids on Shipment Management page:
	  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	And Operator open the shipment detail for the shipment "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" on Shipment Management Page
	When API MM - Operator verifies shipment with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" has events below:
	  | SHIPMENT_CREATED  | Pending |
	  | SHIPMENT_REOPENED | Pending |

  @DeleteCreatedShipments @DeleteMiddleMileDriver @DeleteCreatedMovementSchedules
  Scenario: Shipment Events - Van Inbound Shipment
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 months next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 months next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When API MM - Create "LAND_HAUL" Movement Schedule from "{hub-id}" to "{hub-id-2}" with data below:
	  | startTime | {date: 20 minutes next, yyyy-MM-dd HH:mm:ss}  |
	  | duration  | 00:00:10                                      |
	  | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
	When API MM - Operator creates multiple 1 new shipments with type "LAND_HAUL" from hub id "{hub-id}" to "{hub-id-2}"
	When API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
	When API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
	  | scanType   | SHIPMENT_VAN_INBOUND                     |
	  | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	  | actionType | ADD                                      |
	When API MM - Operator end shipment inbound with movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
	  | scanType | SHIPMENT_VAN_INBOUND                               |
	  | driverId | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id} |
	When API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
	Given Operator go to menu Shipper Support -> Blocked Dates
	When Operator go to menu Inter-Hub -> Shipment Management
	And Operator search shipments by given Ids on Shipment Management page:
	  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	And Operator open the shipment detail for the shipment "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" on Shipment Management Page
	When API MM - Operator verifies shipment with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" has events below:
	  | SHIPMENT_CREATED     | Pending |
	  | SHIPMENT_CLOSED      | Closed  |
	  | ADD_TO_VAN_INBOUND   | Closed  |
	  | SHIPMENT_VAN_INBOUND | Transit |

  @DeleteCreatedShipments @DeleteMiddleMileDriver @DeleteCreatedMovementSchedules
  Scenario: Shipment Events - Hub Inbound Shipment
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 months next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 months next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When API MM - Create "LAND_HAUL" Movement Schedule from "{hub-id}" to "{hub-id-2}" with data below:
	  | startTime | {date: 20 minutes next, yyyy-MM-dd HH:mm:ss}  |
	  | duration  | 00:00:10                                      |
	  | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
	When API MM - Operator creates multiple 1 new shipments with type "LAND_HAUL" from hub id "{hub-id}" to "{hub-id-2}"
	When API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
	When API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
	  | scanType   | SHIPMENT_VAN_INBOUND                     |
	  | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	  | actionType | ADD                                      |
	When API MM - Operator end shipment inbound with movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
	  | scanType | SHIPMENT_VAN_INBOUND                               |
	  | driverId | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id} |
	When API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
	When API MM - Operator "arrive" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
	When API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
	  | scanType   | SHIPMENT_HUB_INBOUND                     |
	  | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	  | actionType | ADD                                      |
	When API MM - Operator "complete" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
	When API MM - Operator end shipment inbound with movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
	  | scanType | SHIPMENT_HUB_INBOUND                               |
	  | driverId | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id} |
	Given Operator go to menu Shipper Support -> Blocked Dates
	When Operator go to menu Inter-Hub -> Shipment Management
	And Operator search shipments by given Ids on Shipment Management page:
	  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	And Operator open the shipment detail for the shipment "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" on Shipment Management Page
	When API MM - Operator verifies shipment with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" has events below:
	  | SHIPMENT_CREATED     | Pending   |
	  | SHIPMENT_CLOSED      | Closed    |
	  | ADD_TO_VAN_INBOUND   | Closed    |
	  | SHIPMENT_VAN_INBOUND | Transit   |
	  | ADD_TO_HUB_INBOUND   | Transit   |
	  | SHIPMENT_HUB_INBOUND | Completed |

  @DeleteCreatedShipments
  Scenario: Shipment Events - Cancel Shipment
	Given API MM - Operator creates multiple 1 new shipments with type "AIR_HAUL" from hub id "{hub-id}" to "{hub-id-2}"
	When API MM - Operator updates shipment "KEY_MM_LIST_OF_CREATED_SHIPMENTS[1]" status to "Cancelled"
	Given Operator go to menu Shipper Support -> Blocked Dates
	When Operator go to menu Inter-Hub -> Shipment Management
	And Operator search shipments by given Ids on Shipment Management page:
	  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
	And Operator open the shipment detail for the shipment "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" on Shipment Management Page
	When API MM - Operator verifies shipment with id "{KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}" has events below:
	  | SHIPMENT_CREATED   | Pending   |
	  | SHIPMENT_CANCELLED | Cancelled |

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
	Given no-op