@OperatorV2 @MiddleMile @Hub @InterHub @PortTripManagement @CreateToFromAirportTrip2
Feature: Airport Trip Management - Create To From Airport Trip 1

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteCreatedPorts @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Create To/from Airport Trip with disabled Origin Hub
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API MM - Operator creates new Port with data below:
      | requestBody | {"type":"Airport","port_code":"GENERATED","port_name":"GENERATED","region":"DEFU","city":"Singapore","system_id":"sg","latitude":-1,"longitude":-1} |
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Given Operator go to menu Inter-Hub -> Port Trip Management
    And Operator verifies that the Port Management Page is opened
    And Operator click on 'Create Tofrom Airport Trip' button in Port Management page
    And Operator verifies "origin facility" with value "{hub-disable-name}" is not shown on Create Airport Trip Port Trip Management page
    And Operator create new airport trip on Port Trip Management page using below data:
      | originFacility      | {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} (Airport) |
      | destinationFacility | {local-hub-3-name}         |
      | departureTime       | 12:00                                      |
      | durationhour        | 01                                         |
      | durationminutes     | 55                                         |
      | departureDate       | {date: 1 days next, yyyy-MM-dd}             |
      | drivers             | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}  |
      | comments            | Created by Automation                      |
    And Verify the new airport trip "Trip {KEY_MM_LIST_OF_CREATED_AIR_HAUL_TRIPS[1].tripId} from {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} (Airport) to {local-hub-3-name} (Warehouse) is created. View Details" created success message on Port Trip Management page

  @DeleteCreatedPorts @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Create To/from Airport Trip with disabled Destination Hub
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API MM - Operator creates new Port with data below:
      | requestBody | {"type":"Airport","port_code":"GENERATED","port_name":"GENERATED","region":"DEFU","city":"Singapore","system_id":"sg","latitude":-1,"longitude":-1} |
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Given Operator go to menu Inter-Hub -> Port Trip Management
    And Operator verifies that the Port Management Page is opened
    And Operator click on 'Create Tofrom Airport Trip' button in Port Management page
    And Operator verifies "destination facility" with value "{hub-disable-name}" is not shown on Create Airport Trip Port Trip Management page
    And Operator create new airport trip on Port Trip Management page using below data:
      | originFacility      | {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} (Airport) |
      | destinationFacility | {local-hub-3-name}         |
      | departureTime       | 12:00                                      |
      | durationhour        | 01                                         |
      | durationminutes     | 55                                         |
      | departureDate       | {date: 1 days next, yyyy-MM-dd}             |
      | drivers             | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}  |
      | comments            | Created by Automation                      |
    And Verify the new airport trip "Trip {KEY_MM_LIST_OF_CREATED_AIR_HAUL_TRIPS[1].tripId} from {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} (Airport) to {local-hub-3-name} (Warehouse) is created. View Details" created success message on Port Trip Management page

  @DeleteCreatedPorts @DeleteCreatedHubs
  Scenario: Create To/from Airport Trip with same Origin and Destination
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API MM - Operator creates new Port with data below:
      | requestBody | {"type":"Airport","port_code":"GENERATED","port_name":"GENERATED","region":"DEFU","city":"Singapore","system_id":"sg","latitude":-1,"longitude":-1} |
    Given Operator go to menu Inter-Hub -> Port Trip Management
    And Operator verifies that the Port Management Page is opened
    And Operator click on 'Create Tofrom Airport Trip' button in Port Management page
    And Operator fill new airport trip on Create Airport Trip Port Trip Management page using data below:
      | originFacility      | {local-hub-3-name} |
      | destinationFacility | {local-hub-3-name} |
    Then Operator verifies same hub error messages on "Create Airport Trip" Port Trip Management page
    And Operator verifies Submit button is disable on Create Airport Trip Port Trip Management page

  @DeleteCreatedPorts @DeleteCreatedHubs
  Scenario: Create To/from Airport Trip with zero duration time
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API MM - Operator creates new Port with data below:
      | requestBody | {"type":"Airport","port_code":"GENERATED","port_name":"GENERATED","region":"DEFU","city":"Singapore","system_id":"sg","latitude":-1,"longitude":-1} |
    Given Operator go to menu Inter-Hub -> Port Trip Management
    And Operator verifies that the Port Management Page is opened
    When Operator fill the departure date for Port Management
      | startDate | {date: 0 days next, yyyy-MM-dd} |
      | endDate   | {date: 1 days next, yyyy-MM-dd} |
    When Operator fill the Origin Or Destination for Port Management
      | originOrDestination | {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} (Airport) |
    And Operator click on 'Load Trips' on Port Management
    Then Verify the parameters of loaded trips in Port Management
      | startDate           | {date: 0 days next, yyyy-MM-dd}                       |
      | endDate             | {date: 1 days next, yyyy-MM-dd}                       |
      | originOrDestination | {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} (Airport) |
    And Operator click on 'Create Tofrom Airport Trip' button in Port Management page
    And Operator fill new airport trip on Create Airport Trip Port Trip Management page using data below:
      | durationminutes | 00 |
      | durationhour    | 00 |
    Then Operator verifies duration time error messages on "Create Airport Trip" Port Trip Management page
    And Operator verifies Submit button is disable on Create Airport Trip Port Trip Management page

  @DeleteCreatedPorts @DeleteCreatedHubs
  Scenario: Create To/from Airport Trip with Flight Departure Date before today
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API MM - Operator creates new Port with data below:
      | requestBody | {"type":"Airport","port_code":"GENERATED","port_name":"GENERATED","region":"DEFU","city":"Singapore","system_id":"sg","latitude":-1,"longitude":-1} |
    Given Operator go to menu Inter-Hub -> Port Trip Management
    And Operator verifies that the Port Management Page is opened
    And Operator click on 'Create Tofrom Airport Trip' button in Port Management page
    Then Operator verifies past date picker "{date: 1 days ago, yyyy-MM-dd}" is disable on "Create Airport Trip" Port Trip Management page
    And Operator verifies Submit button is disable on Create Airport Trip Port Trip Management page

  @DeleteCreatedPorts @DeleteCreatedHubs
  Scenario: Create To/from Airport Trip with Remove the filled value in the mandatory field
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API MM - Operator creates new Port with data below:
      | requestBody | {"type":"Airport","port_code":"GENERATED","port_name":"GENERATED","region":"DEFU","city":"Singapore","system_id":"sg","latitude":-1,"longitude":-1} |
    Given Operator go to menu Inter-Hub -> Port Trip Management
    And Operator verifies that the Port Management Page is opened
    And Operator click on 'Create Tofrom Airport Trip' button in Port Management page
    And Operator fill new airport trip on Create Airport Trip Port Trip Management page using data below:
      | originFacility | {KEY_MM_LIST_OF_CREATED_PORTS[1].portCode} |
    And Operator removes text of "Origin Facility" field on "Create Airport Trip" Port Trip Management page
    Then Operator verifies Mandatory require error message of "Origin Facility" field on "Create Airport Trip" Port Trip Management page
    And Operator verifies Submit button is disable on Create Airport Trip Port Trip Management page

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op
