@OperatorV2 @Sort @Hubs @SortAppUserScope
Feature: Sort App User Scope

  @LaunchBrowser
  Scenario: Create Sort User without Scope SORT_CREATE_SORT_APP_USER
    Given Operator login with client id = "sortappuserwithoutscopeuserid" and client secret = "Sortappuserwithoutscopesecret1"
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Sort App User Management
    When Operator create new Sort App User with detailsV2:
      | firstName              | QATEST                                                               |
      | lastName               | QATEST                                                               |
      | contact                | qa@ninjavan.co                                                       |
      | username               | QATEST                                                               |
      | password               | QATEST                                                               |
      | employmentType         | FULL_TIME                                                            |
      | primaryHub             | sorthub test from QA                                                 |
      | warehouseTeamFormation | QATEST                                                               |
      | position               | QATEST                                                               |
      | comments               | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
   Then Make sure "Insufficient Permissions" notification pop up with "{error-without-create-scope}"

 @LaunchBrowser
Scenario: Edit Sort User without Scope SORT_EDIT_SORT_APP_USER
  Given Operator login with client id = "sortappuserwithoutscopeuserid" and client secret = "Sortappuserwithoutscopesecret1"
  Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Sort App User Management
    And Operator refresh page
    And Operator Load all the Sort App User
    When Operator search sort app user by "User ID" with "SortAutoForEdit"
    When Operator edit the top searched user with data below:
      | firstName              | QATESTEDITFIRSTNAME                                                                   |
      | lastName               | QATESTEDITLASTNAME                                                           |
      | contact                | qa@ninjavan.co                                                       |
      | warehouseTeamFormation | QATESTEDIT                                                    |
      | position               | QATESTEDIT                                                                  |
    Then Make sure "Insufficient Permissions" notification pop up with "{error-without-edit-scope}"

@LaunchBrowser
  Scenario: Sort App Unable Edit Sort User with Scope SORT_CREATE_SORT_APP_USER
    Given Operator login with client id = "sortappuserwithcreatescopeuserid" and client secret = "Sortappuserwithcreatescopesecret1"
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Sort App User Management
    And Operator refresh page
    And Operator Load all the Sort App User
    When Operator search sort app user by "User ID" with "SortAutoForEdit"
    When Operator edit the top searched user with data below:
      | firstName              | QATESTEDITFIRSTNAME                                                                   |
      | lastName               | QATESTEDITLASTNAME                                                           |
      | contact                | qa@ninjavan.co                                                       |
      | warehouseTeamFormation | QATESTEDIT                                                    |
      | position               | QATESTEDIT                                                                  |
    Then Make sure "Insufficient Permissions" notification pop up with "{error-without-edit-scope}"

 @LaunchBrowser
  Scenario: Sort App Unable Create Sort User with Scope SORT_EDIT_SORT_APP_USER
    Given Operator login with client id = "sortappuserwitheditscopeuserid" and client secret = "Sortappuserwitheditscopesecret1"
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Sort App User Management
    When Operator create new Sort App User with detailsV2:
      | firstName              | QATEST                                                               |
      | lastName               | QATEST                                                               |
      | contact                | qa@ninjavan.co                                                       |
      | username               | QATEST                                                               |
      | password               | QATEST                                                               |
      | employmentType         | FULL_TIME                                                            |
      | primaryHub             | sorthub test from QA                                                 |
      | warehouseTeamFormation | QATEST                                                               |
      | position               | QATEST                                                               |
      | comments               | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    Then Make sure "Insufficient Permissions" notification pop up with "{error-without-create-scope}"

  @LaunchBrowser
  Scenario: Sort App Able Create Sort User with Scope SORT_CREATE_SORT_APP_USER
    Given Operator login with client id = "sortappuserwithcreatescopeuserid" and client secret = "Sortappuserwithcreatescopesecret1"
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Sort App User Management
    When Operator create new Sort App User with detailsV2:
      | firstName              | QATESTABC                                                             |
      | lastName               | QATESTABC                                                              |
      | contact                | qa@ninjavan.co                                                       |
      | username               | QATESTABC1234                                                             |
      | password               | QATESTABC1234                                                              |
      | employmentType         | FULL_TIME                                                            |
      | primaryHub             | sorthub test from QA                                                 |
      | warehouseTeamFormation | QATEST                                                              |
      | position               | QATEST                                                              |
      | comments               | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    Then Make sure "Sort App User has been created" notification pop up with "Username"

  @LaunchBrowser
  Scenario: Sort App Able Edit Sort User with Scope SORT_EDIT_SORT_APP_USER
    Given Operator login with client id = "sortappuserwitheditscopeuserid" and client secret = "Sortappuserwitheditscopesecret1"
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Sort App User Management
    And Operator refresh page
    And Operator Load all the Sort App User
    When Operator search sort app user by "User ID" with "SortAutoForEdit"
    When Operator edit the top searched user with data below:
      | firstName              | QATESTEDITFIRSTNAME                                                                   |
      | lastName               | QATESTEDITLASTNAME                                                           |
      | contact                | qa@ninjavan.co                                                       |
      | warehouseTeamFormation | QATESTEDIT                                                    |
      | position               | QATESTEDIT                                                                  |
    Then Make sure "Sort App User has been updated" notification pop up with "Username"

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op
