@OperatorV2 @OperatorV2Part2 @DriverReport @Saas @ForceNotHeadless
Feature: Driver Report
# Sergey Mishanin - Seems Like Fleet -> Driver Report page has been removed

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

#  @DeleteOrArchiveRoute
#  Scenario: Operator generate CSV on Driver Report page (uid:03c84f13-92d8-42a3-8705-3788ce0cab73)
#    Given API Shipper create V4 order using data below:
#      | generateFromAndTo | RANDOM |
#      | v4OrderRequest    | { "service_type":"Parcel", "service_level":"Standard", "parcel_job":{ "is_pickup_required":false, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
#    Given API Operator Global Inbound parcel using data below:
#      | globalInboundRequest | { "hubId":{hub-id} } |
#    Given API Operator create new route using data below:
#      | createRouteRequest | { "zoneId":{zone-id}, "hubId":{hub-id}, "vehicleId":{vehicle-id}, "driverId":{ninja-driver-id} } |
#    Given API Operator add parcel to the route using data below:
#      | addParcelToRouteRequest | { "type":"DD" } |
#    Given API Driver collect all his routes
#    Given API Driver get pickup/delivery waypoint of the created order
#    Given API Operator Van Inbound parcel
#    Given API Operator start the route
#    Given API Driver deliver the created parcel successfully
#    Given Operator go to menu Fleet -> Driver Report
#    When Operator set the filter date to current date
#    When Operator click "Generate CSV" button on Driver Report page
#    Then Operator verify the CSV generated by Driver Report page contains the created route
#
#  @DeleteOrArchiveRoute
#  Scenario: Operator generate Excel on Driver Report page (uid:b9dce546-284c-4dcb-8fef-87486208ef23)
#    Given API Shipper create V4 order using data below:
#      | generateFromAndTo | RANDOM |
#      | v4OrderRequest    | { "service_type":"Parcel", "service_level":"Standard", "parcel_job":{ "is_pickup_required":false, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
#    Given API Operator Global Inbound parcel using data below:
#      | globalInboundRequest | { "hubId":{hub-id} } |
#    Given API Operator create new route using data below:
#      | createRouteRequest | { "zoneId":{zone-id}, "hubId":{hub-id}, "vehicleId":{vehicle-id}, "driverId":{ninja-driver-id} } |
#    Given API Operator add parcel to the route using data below:
#      | addParcelToRouteRequest | { "type":"DD" } |
#    Given API Driver collect all his routes
#    Given API Driver get pickup/delivery waypoint of the created order
#    Given API Operator Van Inbound parcel
#    Given API Operator start the route
#    Given API Driver deliver the created parcel successfully
#    Given Operator go to menu Fleet -> Driver Report
#    When Operator set the filter date to current date
#    When Operator click "Generate Driver Route Excel Report" button on Driver Report page
#    Then Operator verify the Excel generated by Driver Report page contains the created route

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op
