@HubAppUserManagement @Shipment @MiddleMile @ForceNotHeadless
Feature: Hub App User Management

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteHubAppUser
  Scenario: Create Hub User (uid:092570b2-3381-4202-80ec-c4d0c98b5d48)
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator create new Hub App User with details:
      | firstName | lastName   | contact        | username | password | employmentType | hub        | warehouseTeamFormation | position | comments                                                             |
      | QA        | Automation | qa@ninjavan.co | RANDOM   | password | FULL_TIME      | {hub-name} | Middle Mile Team       | QAE      | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown

  Scenario: Create Hub User - Duplicated username (uid:53650108-32ff-4775-98a7-1097b5713075)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    Given DB Operator gets the newest existed username for Hub App
    When Operator create new Hub App User with details:
      | firstName | lastName   | contact        | username   | password | employmentType | employmentStartDate | hub        | warehouseTeamFormation | position | comments                                                             |
      | QA        | Automation | qa@ninjavan.co | DUPLICATED | password | FULL_TIME      | TODAY               | {hub-name} | Middle Mile Team       | QAE      | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    Then Operator verifies that there will be a duplication error toast shown

  Scenario Outline: Create Hub User - Invalid Request - <scenarioName>
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator create new Hub App User with negative scenarios using details:
      | firstName   | lastName   | contact        | username   | password   | employmentType   | employmentStartDate   | hub   | warehouseTeamFormation | position   | comments                                                             |
      | <firstName> | Automation | qa@ninjavan.co | <username> | <password> | <employmentType> | <employmentStartDate> | <hub> | Middle Mile Team       | <position> | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    Then Operator verifies that there will be UI error of empty field of "<errorMessage>" shown
      Examples:
        | scenarioName                   | errorMessage                      | firstName  | username    | password | employmentType | employmentStartDate | hub        | position | hiptest-uid                              |
        | First Name Is Empty            | Please fill First Name            |            | RANDOM      | password | FULL_TIME      | TODAY               | {hub-name} | QAE      | uid:57dad002-b329-4924-a4e7-aa72b12b2bde |
        | Username Is Empty              | Please fill Username              | QA         |             | password | FULL_TIME      | TODAY               | {hub-name} | QAE      | uid:503d1caf-5d89-426b-bcee-1eaf47ca5550 |
        | Password Is Empty              | Please fill Password              | QA         | RANDOM      |          | FULL_TIME      | TODAY               | {hub-name} | QAE      | uid:af7fcfae-fdc1-420d-aea1-a0c17b16bdfb |
        | Employment Type Is Empty       | Please fill Employment Type       | QA         | RANDOM      | password |                | TODAY               | {hub-name} | QAE      | uid:4e743af2-95b3-4a34-9a39-98e3204ea751 |
        | Employment Start Date Is Empty | Please fill Employment Start Date | QA         | RANDOM      | password | FULL_TIME      |                     | {hub-name} | QAE      | uid:fff33da7-b469-4132-ab1b-ba1abe540ca5 |
        | Hub Is Empty                   | Please fill Hub                   | QA         | RANDOM      | password | FULL_TIME      | TODAY               |            | QAE      | uid:8affd32c-0069-4ae3-8d68-34ae0494fe67 |
        | Position is Empty              | Please fill Position              | QA         | RANDOM      | password | FULL_TIME      | TODAY               | {hub-name} |          | uid:94f1afb8-234f-49de-b025-93743973a97c |

  @DeleteHubAppUser
  Scenario: Search Hub User - Show All (uid:e3b18380-3889-4a25-bb3e-2d8de57e1b61)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator create new Hub App User with details:
      | firstName | lastName   | contact        | username | password | employmentType | hub        | warehouseTeamFormation | position | comments                                                             |
      | QA        | Automation | qa@ninjavan.co | RANDOM   | password | FULL_TIME      | {hub-name} | Middle Mile Team       | QAE      | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown

  @DeleteHubAppUser
  Scenario Outline: Search Hub User - By Filter
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator create new Hub App User with details:
      | firstName | lastName   | contact        | username | password | employmentType | hub        | warehouseTeamFormation | position | comments                                                             |
      | QA        | Automation | qa@ninjavan.co | RANDOM   | password | FULL_TIME      | {hub-name} | Middle Mile Team       | QAE      | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator fills the "<filterName>" filter and select the value based on created Hub App User
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown
      Examples:
        | scenarioName                                        | filterName            | hiptest-uid                              |
        | Search Hub App User by Hub Filter                   | hub                   | uid:f7631336-9b50-4dc2-9cf8-a6d2bc4ffa7b |
        | Search Hub App User by Employment Type Filter       | employment type       | uid:7a762940-629d-42e8-9b5a-d0e0292a1573 |
        | Search Hub App User by Employment Start Date Filter | employment start date | uid:60386eb1-cc9f-4665-b15b-6671302a3173 |
        | Search Hub App User by Status Filter                | status                | uid:64b6595e-2641-4b46-ba3f-b3f24917e234 |
        | Search Hub App User by Multiple Filter              | multiple              | uid:51fe905f-8704-481c-a1fa-e5b177f684b1 |

  Scenario: Clearing the selected filters (uid:7b4025d2-a1f3-4b56-94d6-16b4744efc22)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator fills the filter without creating Hub App User
    And Operator clicks on the clear filter button on the Hub App User Management Page
    Then Operator verifies that the filter is blank

  @DeleteHubAppUser
  Scenario Outline: Update Hub User - Update Details - <scenarioName> (<hiptest-uid>)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator create new Hub App User with details:
      | firstName | lastName   | contact        | username | password | employmentType | hub        | warehouseTeamFormation | position | comments                                                             |
      | QA        | Automation | qa@ninjavan.co | RANDOM   | password | FULL_TIME      | {hub-name} | Middle Mile Team       | QAE      | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown
    And Operator edits the existed Hub App User with details:
      | firstName   | lastName   | contact   | password   | employmentType   | employmentStatus   | hub   | warehouseTeamFormation   | position   | comments   |
      | <firstName> | <lastName> | <contact> | <password> | <employmentType> | <employmentStatus> | <hub> | <warehouseTeamFormation> | <position> | <comments> |
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown
    Examples:
      | scenarioName                                                                         | firstName             | lastName              | contact                       | password              | employmentType        | employmentStatus      | hub                   | warehouseTeamFormation | position              | comments                                                             | hiptest-uid                              |
      | Update Personal Detail - Normal Flow                                                 | Automation            | QA                    | tristania.siagian@ninjavan.co | Ninjitsu89            | FULL_TIME             | ACTIVE                | {hub-name}            | Middle Mile Team       | QAE                   | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:79991438-00c0-4f98-a544-98fb454ecae1 |
      | Update Personal Details - Last Name is Empty (Non-Negative Scenario)                 | QA                    |                       | qa@ninjavan.co                | password              | FULL_TIME             | ACTIVE                | {hub-name}            | Middle Mile Team       | QAE                   | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:f2436dd6-dd25-4054-98d3-6684523bf655 |
      | Update Personal Detail - Contact Detail is Empty (Non-Negative Scenario)             | QA                    | Automation            |                               | password              | FULL_TIME             | ACTIVE                | {hub-name}            | Middle Mile Team       | QAE                   | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:5fc0df6c-5367-4930-84f4-5c5f0c714e00 |
      | Update Personal Details - Password is Empty (Non-Negative Scenario)                  | QA                    | Automation            | qa@ninjavan.co                |                       | FULL_TIME             | ACTIVE                | {hub-name}            | Middle Mile Team       | QAE                   | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:d71fdd74-9a5a-4652-90ea-c4bb463993f9 |
      | Update Employee Details  - Normal Flow                                               | QA                    | Automation            | qa@ninjavan.co                | password              | PART_TIME             | ACTIVE                | JKB                   | Middle Mile Team       | QA Engineer           | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:9574e23c-223e-40dc-bc17-e6cd8d409035 |
      | Update Employee Details - Warehouse Team Formation is Empty (Non-Negative Scenario)  | QA                    | Automation            | qa@ninjavan.co                | password              | FULL_TIME             | ACTIVE                | {hub-name}            |                        | QA Engineer           | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:530df727-7845-49e8-bee4-3563e669c93b |
      | Update Activity of the Hub App User                                                  | QA                    | Automation            | qa@ninjavan.co                | password              | FULL_TIME             | INACTIVE              | {hub-name}            | Middle Mile Team       | QA Engineer           | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. | uid:8e9f36ce-f351-4d5b-aa06-ce53ea6066e4 |
      | Update Additional Details  - Normal Flow                                             | QA                    | Automation            | qa@ninjavan.co                | password              | FULL_TIME             | ACTIVE                | {hub-name}            | Middle Mile Team       | QA Engineer           | This is edited by automation at {gradle-current-date-yyyy-MM-dd}.    | uid:67dc5810-1f9f-478c-8d44-78d3f7719c8b |
      | Update Additional Details - Comment is Empty (Non-Negative Scenario)                 | QA                    | Automation            | qa@ninjavan.co                | password              | FULL_TIME             | ACTIVE                | {hub-name}            | Middle Mile Team       | QA Engineer           |                                                                      | uid:c717ae8c-2f01-4bab-9cd4-5c6fdf45ac5d |

  @DeleteHubAppUser
  Scenario Outline: Update Hub User - Update Details Negative Scenario - <scenarioName> (<hiptest-uid>)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Access Control -> Hub App User Management
    When Operator create new Hub App User with details:
      | firstName | lastName   | contact        | username | password | employmentType | hub        | warehouseTeamFormation | position | comments                                                             |
      | QA        | Automation | qa@ninjavan.co | RANDOM   | password | FULL_TIME      | {hub-name} | Middle Mile Team       | QAE      | This is generated by automation at {gradle-current-date-yyyy-MM-dd}. |
    And Operator Load all the Hub App User
    Then Operator verifies that the newly created Hub App User will be shown
    And Operator edits the existed Hub App User with negative scenario using details:
      | firstName   | position   |
      | <firstName> | <position> |
    Then Operator verifies that there will be UI error of empty field of "<errorMessage>" shown
    Examples:
      | scenarioName                                   | firstName             | position | errorMessage           | hiptest-uid                              |
      | Update Personal Details - First Name is Empty  |                       | QAE      | Please fill First Name | uid:fb68011b-bb75-41c6-a430-f2cf3bdad246 |
      | Update Employee Details - Position is Empty    | QA                    |          | Please fill Position   | uid:3df63bee-6dc6-47a8-9b5e-c391b66e24a9 |

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op
