@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @SearchDriver
Feature: Middle Mile Driver Management - Search Driver

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Load All Drivers (uid:fc8158aa-ed1c-4c94-866a-bb4ced22ab35)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page on "https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?showall=true"
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Hub (uid:c629d70f-53d3-4327-805f-e988e6b1e25c)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?hubIds={hub-id} |
      | Hub | {hub-name}                                                                 |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Employment Status Active (uid:9d52e56e-6edf-437b-ac09-5e9ef38cf683)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=active |
      | Employment Status | Active                                                                             |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Employment Status Inactive (uid:723b57eb-3d0b-421b-be8b-681078759a88)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 2 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=inactive |
      | Employment Status | Inactive                                                                             |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - License Status Active (uid:dd6df1fc-da8a-49b8-9abd-6ad4d87622ad)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url            | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?licenseStatus=active |
      | License Status | Active                                                                          |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - License Status Inactive (uid:3be300e1-e557-41f1-8dca-ba77bf01f1e9)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days ago, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url            | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?licenseStatus=inactive |
      | License Status | Inactive                                                                          |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Employment Status Inactive and License Status Inactive (uid:f926dc6b-2165-444c-9f30-c0c35fa2c7db)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days ago, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 2 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=inactive&licenseStatus=inactive |
      | Employment Status | Inactive                                                                                                    |
      | License Status    | Inactive                                                                                                    |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Employment Status Active and License Status Active(uid:8a8df869-aa86-438d-9ad9-7e0ae0497d1b)
    Given Operator go to menu Shipper Support -> Blocked Dates
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=active&licenseStatus=active |
      | Employment Status | Active                                                                                                  |
      | License Status    | Active                                                                                                  |
    Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op