@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @SearchDriver5
Feature: Middle Mile Driver Management - Search Driver 5

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
	Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is B
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"B","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is B1
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"B1","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is B2
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"B2","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is C
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"C","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is Restriction 1
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Restriction 1","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is Restriction 2
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Restriction 2","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is Restriction 3
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Restriction 3","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is Restriction 3
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Restriction 3","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches the "LICENSE TYPE" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Filter Driver on License Type column - PH - License Type is all types
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"B,B1,B2,C,Restriction 1,Restriction 2,Restriction 3","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id-ph}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	And Operator searches all types of the license type of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]"

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
	Given no-op