@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @SearchDriver2
Feature: Middle Mile Driver Management - Search Driver 2

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
	Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Employment Status Inactive and License Status Active(uid:74fe1b41-427f-4d03-b263-bf4024b3df50)
	Given Operator go to menu Shipper Support -> Blocked Dates
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 1 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=inactive&licenseStatus=active |
	  | Employment Status | Inactive                                                                                                  |
	  | License Status    | Active                                                                                                    |
	Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Employment Status Active and License Status Inactive (uid:8fe481c5-13db-4dc6-be5b-9a7c67cc6c93)
	Given Operator go to menu Shipper Support -> Blocked Dates
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 0 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=active&licenseStatus=inactive |
	  | Employment Status | Active                                                                                                    |
	  | License Status    | Inactive                                                                                                  |
	Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Load Driver by Filter - Hub, Employment Status Inactive and License Status Inactive (uid:e1d54146-6e85-4b1b-884e-e7f1f9a89070)
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator get info of hub details id "{hub-id}"
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 0 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 1 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url               | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?employmentStatus=inactive&hubIds=<id>&licenseStatus=inactive |
	  | Hub               | {KEY_HUB_INFO.name}                                                                                                     |
	  | Employment Status | Inactive                                                                                                                |
	  | License Status    | Inactive                                                                                                                |
	Then Operator verifies driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is shown in Middle Mile Driver page

  @DeleteMiddleMileDriver
  Scenario: Search Driver on Search Field Name (uid:f1863d5a-2151-4430-98e0-228cbfbd9853)
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?hubIds={hub-id} |
	  | Hub | {hub-name}                                                                 |
	Then Operator searches the "NAME" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @HappyPath @DeleteMiddleMileDriver
  Scenario: Search Driver on Search Field ID (uid:dcebd212-12c5-42e6-82fb-76e894f36d73)
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?hubIds={hub-id} |
	  | Hub | {hub-name}                                                                 |
	Then Operator searches the "ID" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Search Driver on Search Field Username (uid:5975fcb7-c611-4aa3-9e01-5af1d3ea036b)
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?hubIds={hub-id} |
	  | Hub | {hub-name}                                                                 |
	Then Operator searches the "USERNAME" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @DeleteMiddleMileDriver
  Scenario: Search Driver on Search Field Hub (uid:e2590d24-9767-4daf-b9e7-148929184731)
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"{default-driver-vendor-type}","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true,"vendor_id":{default-driver-vendor-id}} |
	Then Operator verifies UI elements in Middle Mile Driver Page with data below
	  | url | https://operatorv2-qa.ninjavan.co/#/sg/middle-mile-drivers?hubIds={hub-id} |
	  | Hub | {hub-name}                                                                 |
	Then Operator searches the "HUB" of "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" and verifies the value is correct

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
	Given no-op