@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @UpdateDriver2
Feature: Middle Mile Driver Management - Update Driver 2

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
	Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : In-House - Full Time
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Part-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "In-House - Full-Time"
	And API MM - Operator verifies "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : In-House - Part-Time
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "In-House - Part-Time"
	And API MM - Operator verifies "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : Outsourced - Subcon
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Outsourced - Subcon"
	And API MM - Operator verifies "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : Outsourced - Vendors
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Outsourced - Vendors|{default-driver-vendor-name-sg}"
	And API MM - Operator verifies "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct
	And API MM - Operator verifies "vendorName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : Outsourced - Vendors but No Vendor Selected
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Outsourced - Vendors|-"
  	Then Operator clicks "Save" button on Middle Mile Drivers Page
	Then Operator verifies error message on "Vendor's Name" field on the middle mile driver is shown

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : Outsourced - Manpower Agency
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Outsourced - Manpower Agency|{default-driver-manpower-agency-sg}"
	And API MM - Operator verifies "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct
	And API MM - Operator verifies "vendorName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Type : Outsourced - Manpower Agency but No Vendor Selected
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "employmentType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Outsourced - Manpower Agency|-"
  	Then Operator clicks "Save" button on Middle Mile Drivers Page
	Then Operator verifies error message on "Vendor's Name" field on the middle mile driver is shown

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
	Given no-op