@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @UpdateDriver4
Feature: Middle Mile Driver Management - Update Driver 4

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
	Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is B
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"B1","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "B1" value and update with "{default-license-type-ph}" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "{default-license-type-ph}" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is B1
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "B1" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "B1" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is B2
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "B2" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "B2" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is B2
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "B2" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "B2" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is C
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "C" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "C" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is Restriction 1
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "Restriction 1" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "Restriction 1" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is Restriction 2
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "Restriction 2" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "Restriction 2" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is Restriction 3
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "Restriction 3" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "Restriction 3" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is all type
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value and update with "all types" on the middle mile driver page
	Then DB Operator verifies driver "licenseType" with username "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username}" and value "B,B1,B2,C,Restriction 1,Restriction 2,Restriction 3" is updated

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - PH - License Type is not selected
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator change the country to "Philippines"
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"{default-license-type-ph}","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit License Type with uncheck "{default-license-type-ph}" value on the middle mile driver page
	Then Operator verifies error message on "License Type" field on the middle mile driver is shown

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
	Given no-op