@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @UpdateDriver
Feature: Middle Mile Driver Management - Update Driver

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Name (uid:c6c8e619-1437-4a8d-ab3e-954e9e1ad863)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator change the country to "Singapore"
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "displayName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "DRIVER EDITED NAME"
    And API MM - Operator verifies "displayName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Contact Number (uid:9ec5adc6-aa82-40d5-93a4-a593033154fb)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "contactDetails" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "{default-phone-number}"
    And API MM - Operator verifies "contactDetails" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Hub (uid:1892577e-d469-45dc-8ad5-48cbb0ddbf2a)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "hubName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "{hub-name-2}"
    And API MM - Operator verifies "hubName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - License Number (uid:869dea40-d9e0-4a59-82b0-59b1f503bca5)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "licenseNumber" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "D{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id"
    And API MM - Operator verifies "licenseNumber" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - Expiry Date (uid:def761b9-8aca-463d-ba5c-1641915a3477)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "licenseExpiryDate" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "{date: 1 days next, yyyy-MM-dd}"
    And API MM - Operator verifies "licenseExpiryDate" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver License - License Type (uid:213c5760-5212-4fd8-b0be-9806886da126)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "licenseType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Class 3"
    And API MM - Operator verifies "licenseType" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment Start Date (uid:51d4a35e-8453-4c9a-9b35-3f16638b22e8)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "employmentStartDate" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "{date: 1 days next, yyyy-MM-dd}"
    And API MM - Operator verifies "employmentStartDate" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Employment Details - Employment End Date (uid:e2b5d826-6669-46f0-8a08-b8e00dd6c51f)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator refresh page v1
    Given Operator go to menu Inter-Hub -> Middle Mile Drivers
    And Operator verifies middle mile driver management page is loaded
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    Then Operator verifies UI elements in Middle Mile Driver Page with data below
      | url               | {operator-portal-base-url}/#/{country-code-lower}/middle-mile-drivers?employmentStatus=active&hubIds={hub-id}&licenseStatus=active |
      | Hub               | {hub-name}                                                                                                                         |
      | Employment Status | Active                                                                                                                             |
      | License Status    | Active                                                                                                                             |
    Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
    When Operator clicks edit button on the middle mile driver page
    And Operator edit "employmentEndDate" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "{date: 1 days next, yyyy-MM-dd}"
    And API MM - Operator verifies "employmentEndDate" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op