@OperatorV2 @MiddleMile @Hub @InterHub @MiddleMileDrivers @UpdateDriver3
Feature: Middle Mile Driver Management - Update Driver 3

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
	Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - First Name
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "firstName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "AutomationFirstName"
	And API MM - Operator verifies "firstName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Last Name
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "lastName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "AutomationLastName"
	And API MM - Operator verifies "lastName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Display Name
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "displayName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Display Name Automation"
	And API MM - Operator verifies "displayName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - First Name with contains either Letters, Numbers, Hyphens, Underscores, and Parentheses
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "firstName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Automation_First_Name"
	Then Operator clicks "Save" button on Middle Mile Drivers Page
	Then Operator verifies toast with message "Request failed with status code 400" is shown on edit Middle Mile Driver popup

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Last Name with contains either Letters, Numbers, Hyphens, Underscores, and Parentheses
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "lastName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Automation_Last_Name"
	Then Operator clicks "Save" button on Middle Mile Drivers Page
	Then Operator verifies toast with message "Request failed with status code 400" is shown on edit Middle Mile Driver popup

  @DeleteMiddleMileDriver
  Scenario: Update Driver Details - Display Name with contains either Letters, Numbers, Hyphens, Underscores, and Parentheses
	Given Operator go to menu Shipper Support -> Blocked Dates
	Given Operator go to menu Inter-Hub -> Middle Mile Drivers
	And Operator verifies middle mile driver management page is loaded
	When API MM - Operator creates new Middle Mile Driver with data below:
	  | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 days next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
	When Operator clicks "Load Drivers" button on Middle Mile Drivers Page
	Then Operator searches by "id" with value "{KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].driverId}"
	When Operator clicks edit button on the middle mile driver page
	And Operator edit "displayName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" on edit driver dialog with value "Automation_Display_Name"
	And API MM - Operator verifies "displayName" of Middle Mile Driver "KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]" is correct

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
	Given no-op