@OperatorV2 @MiddleMile @Hub @InterHub @MovementTrip @TripCancelTrip
Feature: Movement Trip - Cancel Trip

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Cancel Trip - Trip Status Pending (uid:318c9c20-adae-40f0-8094-e82d986008e6)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
      | drivers  | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "cancel" icon on the action column
    And Operator verifies the Cancel Trip button is "disable"
    And Operator select Cancellation Reason on Cancel Trip Page
    Then Operator verifies the Cancellation Reason are correct
    And Operator verifies the Cancel Trip button is "enable"
    When Operator clicks "Cancel Trip" button on cancel trip dialog
    Then Operator verifies that there will be a movement trip "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" cancelled toast shown
    And Operator verifies movement trip shown has status value "cancelled"
    And API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" has event below:
      | event   | cancelled  |
      | status  | cancelled  |
      | userId  | automation |
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Cancel Trip - Trip Status Transit (uid:c4b7c24e-e9c1-42a6-8bcd-299f0bde7d68)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
      | drivers  | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}" exist
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When Operator clicks on "cancel" icon on the action column
    And Operator verifies the Cancel Trip button is "disable"
    And Operator select Cancellation Reason on Cancel Trip Page
    Then Operator verifies the Cancellation Reason are correct
    And Operator verifies the Cancel Trip button is "enable"
    When Operator clicks "Cancel Trip" button on cancel trip dialog
    Then Operator verifies toast with message "Request failed with status code 400" is shown on movement page
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator searches for Movement Trip based on status "transit"
    Then Operator verifies movement trip shown has status value "transit"
    And API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" has event below:
      | event   | DEPARTED        |
      | status  | TRANSIT         |
      | userId  | AUTOMATION      |
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  @DeleteCreatedHubs
  Scenario: Call Off Cancel Trip - Trip Status Pending (uid:770109ba-1146-459c-8be6-26eba77c303d)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}" exist
    When Operator clicks on "cancel" icon on the action column
    And Operator verifies the Cancel Trip button is "disable"
    And Operator select Cancellation Reason on Cancel Trip Page
    Then Operator verifies the Cancellation Reason are correct
    And Operator verifies the Cancel Trip button is "enable"
    When Operator clicks "No" button on cancel trip dialog
    Then Operator verifies movement trip shown has status value "pending"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Call Off Cancel Trip - Trip Status Transit (uid:9003a32c-c483-4a4c-981a-b331abf7b684)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
      | drivers  | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}" exist
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
#    And API Operator updates movement trip status to transit
    When Operator clicks on "cancel" icon on the action column
    And Operator clicks "No" button on cancel trip dialog
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}" exist
    Then Operator verifies movement trip shown has status value "transit"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  @DeleteCreatedHubs
  Scenario: Cannot Cancel Invalid Trip - Trip status Cancelled (uid:dba2be77-0bd7-439d-9c6e-58c5bd07ddd1)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}" exist
    When Operator clicks on "cancel" icon on the action column
    And Operator verifies the Cancel Trip button is "disable"
    And Operator select Cancellation Reason on Cancel Trip Page
    Then Operator verifies the Cancellation Reason are correct
    And Operator verifies the Cancel Trip button is "enable"
    And Operator clicks "Cancel Trip" button on cancel trip dialog
    And Operator verifies that there will be a movement trip "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" cancelled toast shown
    And Operator searches for Movement Trip based on status "cancelled"
    Then Operator verifies "cancel" button disabled

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Cannot Cancel Invalid Trip - Trip status Completed (uid:6b520ff1-b954-4877-a9c3-985ac92b4fc4)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
      | drivers  | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator "force complete" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}" exist
    Then Operator verifies "cancel" button disabled

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Cancel Trip via Trip Detail - Departure Trip (uid:a16dfa06-77cd-4fd7-9367-50bd8900c15e)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
      | drivers  | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    And Operator clicks Cancel Trip button on Department page
    And Operator verifies the Cancel Trip button is "disable"
    And Operator select Cancellation Reason on Cancel Trip Page
    Then Operator verifies the Cancellation Reason are correct
    And Operator verifies the Cancel Trip button is "enable"
    When Operator clicks Cancel Trip button on Cancel page
    Then Operator verifies that there will be a movement trip "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" cancelled toast shown
    And API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" has event below:
      | event   | cancelled  |
      | status  | cancelled  |
      | userId  | automation |

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Cancel Trip via Trip Detail - Archived Trip (uid:6f2b6b39-9003-428b-bd61-cd009195914f)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration | 00:00:10 |
      | drivers  | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1] |
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And DB Hub - Shift Movement Trip with Id "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" Expected Start Time to -24 Hours Relative to Now
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Archive" tab
    And Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator searches and selects the "destination hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    And Operator clicks Cancel Trip button on Department page
    And Operator verifies the Cancel Trip button is "disable"
    And Operator select Cancellation Reason on Cancel Trip Page
    Then Operator verifies the Cancellation Reason are correct
    And Operator verifies the Cancel Trip button is "enable"
    When Operator clicks Cancel Trip button on Cancel page
    Then Operator verifies that there will be a movement trip "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" cancelled toast shown
    And API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" has event below:
      | event   | cancelled  |
      | status  | cancelled  |
      | userId  | automation |

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op
