@Hub @InterHub @MiddleMile @TripManagement @MovementTrip @UpdateTrip2
Feature: Movement Trip - Update Trip 2

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Force Complete Departed Trip via Trip Details page - In Transit Trip
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 4 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[3].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[4].id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[3].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[4].name}" exist
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | arrive                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[3].id}    |
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator departs trip and force complete when showing warning for driver in another trip
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"
    And Operator depart trip
    And Operator verifies trip message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" display on Movement Trip details page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Force Complete Arrived Trip via Trip Details page - Incomplete Trip
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 4 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator "arrive" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[3].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[4].id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[3].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[4].name}" exist
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | arrive                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[3].id}    |
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator departs trip and force complete when showing warning for driver in another trip
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"
    And Operator depart trip
    And Operator verifies trip message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" display on Movement Trip details page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Force Complete Departed Trip via Movement Trip Table page - In Transit Trip
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 4 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[3].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[4].id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[3].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[4].name}" exist
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[3].id}    |
    When Operator departs trip and force complete when showing warning for driver in another trip
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"
    And Operator depart trip
    And Operator verifies trip message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" display on Movement Trip details page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Force Complete Arrived Trip via Movement Trip Table page - Incomplete Trip
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 4 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator "arrive" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[3].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[4].id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[3].name}"
    And Operator clicks on Load Trip Button
    And Operator verifies a trip to destination hub "{KEY_SORT_LIST_OF_CREATED_HUBS[4].name}" exist
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[3].id}    |
    When Operator departs trip and force complete when showing warning for driver in another trip
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"
    And Operator depart trip
    And Operator verifies trip message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" display on Movement Trip details page

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op