@Hub @InterHub @MiddleMile @TripManagement @MovementTrip @UpdateTrip3
Feature: Movement Trip - Update Trip

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Departure with single Driver Still In Transit (uid:46df4679-d92c-4b16-b140-d8a3a28c3aa4)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 4 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[3].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[4].id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[3].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And Operator departs trip and force complete when showing warning for driver in another trip
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"
    And Operator depart trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Complete (uid:b6d4ffd1-5960-48c6-bd09-4b311909f9e7)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Arrival" tab
    When Operator searches and selects the "destination hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And Operator arrive trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} arrived" is shown on movement page
    When Operator complete trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} has completed" is shown on movement page
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Can Register Trip Departure With Driver from deleted Hub Relation (uid:75a4f2b5-de52-4946-94c9-47269dbb7f23)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
    When API MM - Operator deletes all Movement Schedules from Hub Relation "KEY_MM_LIST_OF_CREATED_HUB_RELATIONS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And Operator clicks on "assign_driver" icon on the action column
    And Operator assign driver "({KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].username})" to created movement trip
    Then Operator verifies toast with message "1 driver(s) successfully assigned to the trip" is shown on movement page
    And Operator depart trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Departure with Multiple Drivers Still In Transit for Multiple Different Trips (uid:d7dbab63-4e63-4f98-b1f2-5b9c18e5a39c)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 3 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1]   |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[3].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[2]   |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 20 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1],KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[2] |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And Operator departs trip with driver
    Then Operator verifies toast with following messages is shown on movement page without closing:
      | Driver {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].displayName} is still in trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} from {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} to {hub-relation-destination-hub-name} |
      | Driver {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[2].displayName} is still in trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} from {KEY_SORT_LIST_OF_CREATED_HUBS[3].name} to {hub-relation-destination-hub-name} |
    And Operator click force trip completion
    Then Operator verifies toast with following messages is shown on movement page without closing:
      | Driver {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].displayName} is still in trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} from {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} to {hub-relation-destination-hub-name} |
      | Driver {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[2].displayName} is still in trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} from {KEY_SORT_LIST_OF_CREATED_HUBS[3].name} to {hub-relation-destination-hub-name} |
    And Operator click force trip completion
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]" status is "COMPLETED"
    Then API MM - Operator verifies Movement Trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2]" status is "COMPLETED"
    And Operator depart trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[3].id} departed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Departure with Multiple Drivers Still In Transit for Same Trip (uid:4203b43a-1aec-43dd-b791-84e4a071f791)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 15 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And Operator departs trip with driver
    Then Operator verifies one of toast with message is shown on movement page without closing
      | Driver {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].displayName}, {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[2].displayName} is still in trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} from {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} to {hub-relation-destination-hub-name} |
      | Driver {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[2].displayName}, {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].displayName} is still in trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} from {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} to {hub-relation-destination-hub-name} |
    And Operator click force trip completion
    And Operator depart trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[2].id} departed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Departure via Trip Details page - Status Pending and not Archived (uid:ba270a28-8fc2-48e1-930f-58c434afb19b)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator depart trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} departed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Departure via Trip Details page - Status Pending and Archived (uid:08867801-23a7-459c-9362-fea46e90f792)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And DB Hub - Shift Movement Trip with Id "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" Expected Start Time to -24 Hours Relative to Now
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Archive" tab
    And Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator searches and selects the "destination hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator depart trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} departed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Register Trip Arrival via Trip Details page (uid:11626b18-5a20-409b-97c2-fb66d7d2f7ca)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    And Operator arrive trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} arrived" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Force Complete Trip via Trip Details page - Arrived Trip (uid:d91e960c-eb51-416a-8ad4-815d66e569ad)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator "arrive" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Arrival" tab
    When Operator searches and selects the "destination hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    And Operator force complete trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} has completed" is shown on movement page

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: Force Complete Trip via Trip Details page - Transit Trip in Archived (uid:08867801-23a7-459c-9362-fea46e90f792)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator "arrive" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And DB Hub - Shift Movement Trip with Id "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" Expected Start Time to -24 Hours Relative to Now
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Archive" tab
    And Operator searches and selects the "origin hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[1].name}"
    And Operator searches and selects the "destination hub" with value "{KEY_SORT_LIST_OF_CREATED_HUBS[2].name}"
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    And Operator force complete trip
    Then Operator verifies toast with message "Trip {KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id} has completed" is shown on movement page

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op