@OperatorV2 @MiddleMile @Hub @InterHub @MovementTrip @ViewTrip
Feature: Movement Trip - View Trips

  @LaunchBrowser @ShouldAlwaysRun
  Scenario: Login to Operator Portal V2
    Given Operator login with username = "{operator-portal-uid}" and password = "{operator-portal-pwd}"

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: View Departure Trip Details - Trip Events (uid:fd9d635c-5dc2-4e14-8344-20b7acb3f984)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{hub-relation-destination-hub-id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    And Operator sets movement trips filter with data below:
      | tab       | Departure                               |
      | originHub | {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} |
    And Operator clicks on Load Trip Button
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    Then Operator verifies trips shown on "departure" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  @DeleteCreatedHubs @DeleteMiddleMileDriver
  Scenario: View Arrival Trip Detail - Trip Events (uid:567dc293-b7c3-441a-8f00-2998fad953a9)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    And Operator refresh page
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator sets movement trips filter with data below:
      | tab            | Arrival                                 |
      | destinationHub | {KEY_SORT_LIST_OF_CREATED_HUBS[2].name} |
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | arrive                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[2].id}    |
    Then Operator verifies trips shown on "arrival" tab of Movement Trip page are the same as "KEY_MM_LIST_OF_SEARCHED_MOVEMENT_TRIPS"
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  Scenario: View Archived Trip Details - Trip Events (uid:f88425c2-6cb1-44d5-a9ff-d87abf1cf31b)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Archive" tab
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    And API Operator gets the count of the Trip Management with data:
      | movementTripType | archive |
      | days             | 0       |
      | hubId            | 0       |
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened

  @DeleteCreatedHubs @DeleteMiddleMileDriver @DeleteCreatedShipments
  Scenario: View Departure Trip Details - Shipment (uid:26f6c205-bc90-4ce8-991f-77a95f38f4fe)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given API Order - Shipper create multiple V4 orders using data below:
      | shipperClientId     | {shipper-v4-client-id}                                                                                                                                                                                                                                                                                                          |
      | shipperClientSecret | {shipper-v4-client-secret}                                                                                                                                                                                                                                                                                                      |
      | generateFromAndTo   | RANDOM                                                                                                                                                                                                                                                                                                                          |
      | v4OrderRequest      | { "service_type":"Return", "service_level":"Standard", "parcel_job":{ "is_pickup_required":true, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    Given API MM - Operator creates multiple 2 new shipments with type "LAND_HAUL" from hub id "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}"
    Given API Sort - Operator adds order to shipment:
      | shipmentId | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}                                                                                                        |
      | request    | {"order_country":"sg","tracking_id":"{KEY_LIST_OF_CREATED_TRACKING_IDS[1]}","hub_id":{KEY_SORT_LIST_OF_CREATED_HUBS[1].id},"action_type":"ADD"} |
    Given API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
    Given API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
      | scanType   | SHIPMENT_VAN_INBOUND                     |
      | actionType | ADD                                      |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    And Operator sets movement trips filter with data below:
      | tab       | Departure                               |
      | originHub | {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} |
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator click on Shipment tab
    Then Operator verifies the elements on Shipment tab are correct

  @DeleteCreatedHubs @DeleteMiddleMileDriver @DeleteCreatedShipments
  Scenario: View Arrival Trip Details - Shipment (uid:59055ed6-2715-44b3-b4a2-52de02393fea)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given API Order - Shipper create multiple V4 orders using data below:
      | shipperClientId     | {shipper-v4-client-id}                                                                                                                                                                                                                                                                                                          |
      | shipperClientSecret | {shipper-v4-client-secret}                                                                                                                                                                                                                                                                                                      |
      | generateFromAndTo   | RANDOM                                                                                                                                                                                                                                                                                                                          |
      | v4OrderRequest      | { "service_type":"Return", "service_level":"Standard", "parcel_job":{ "is_pickup_required":true, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    Given API MM - Operator creates multiple 2 new shipments with type "LAND_HAUL" from hub id "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}"
    Given API Sort - Operator adds order to shipment:
      | shipmentId | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}                                                                                                        |
      | request    | {"order_country":"sg","tracking_id":"{KEY_LIST_OF_CREATED_TRACKING_IDS[1]}","hub_id":{KEY_SORT_LIST_OF_CREATED_HUBS[1].id},"action_type":"ADD"} |
    Given API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
    Given API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
      | scanType   | SHIPMENT_VAN_INBOUND                     |
      | actionType | ADD                                      |
    Given API MM - Operator end shipment inbound with movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanType | SHIPMENT_VAN_INBOUND                               |
      | driverId | {KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS[1].id} |
    And API MM - Operator "depart" movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]"
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    When Operator clicks on "Arrival" tab
    And Operator sets movement trips filter with data below:
      | tab            | Arrival                                 |
      | destinationHub | {KEY_SORT_LIST_OF_CREATED_HUBS[2].name} |
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator click on Shipment tab
    Then Operator verifies the elements on Shipment tab are correct

  @DeleteCreatedHubs @DeleteMiddleMileDriver @DeleteCreatedShipments
  Scenario: View Archived Trip Details - Shipment (uid:72ab7c07-33d4-4040-9197-b95f06f35eb5)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given API Order - Shipper create multiple V4 orders using data below:
      | shipperClientId     | {shipper-v4-client-id}                                                                                                                                                                                                                                                                                                          |
      | shipperClientSecret | {shipper-v4-client-secret}                                                                                                                                                                                                                                                                                                      |
      | generateFromAndTo   | RANDOM                                                                                                                                                                                                                                                                                                                          |
      | v4OrderRequest      | { "service_type":"Return", "service_level":"Standard", "parcel_job":{ "is_pickup_required":true, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    Given API MM - Operator creates multiple 2 new shipments with type "LAND_HAUL" from hub id "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}"
    Given API Sort - Operator adds order to shipment:
      | shipmentId | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}                                                                                                        |
      | request    | {"order_country":"sg","tracking_id":"{KEY_LIST_OF_CREATED_TRACKING_IDS[1]}","hub_id":{KEY_SORT_LIST_OF_CREATED_HUBS[1].id},"action_type":"ADD"} |
    Given API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
    Given API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
      | scanType   | SHIPMENT_VAN_INBOUND                     |
      | actionType | ADD                                      |
    And API MM - Operator searches Movement Trips with movement type with data below:
      | action       | depart                                   |
      | movementType | LAND_HAUL                                |
      | from         | {date: 0 days next, yyyy-MM-dd} 00:00:00 |
      | to           | {date: 0 days next, yyyy-MM-dd} 23:59:59 |
      | hubId        | {KEY_SORT_LIST_OF_CREATED_HUBS[1].id}    |
    And DB Hub - Shift Movement Trip with Id "{KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1].id}" Expected Start Time to -24 Hours Relative to Now
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator verifies movement Trip page is loaded
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    And Operator sets movement trips filter with data below:
      | tab            | Archive                                 |
      | originHub      | {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} |
      | destinationHub | {KEY_SORT_LIST_OF_CREATED_HUBS[2].name} |
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator click on Shipment tab
    Then Operator verifies the elements on Shipment tab are correct

  @DeleteCreatedHubs @DeleteMiddleMileDriver @DeleteCreatedShipments
  Scenario: View Trip Details with pagination (uid:4d613467-2aa5-4603-a9dc-f5e859adbb4b)
    Given Operator go to menu Shipper Support -> Blocked Dates
    Given API Sort - Operator creates 2 new generated "CROSSDOCK" hubs
    When API MM - Operator creates new Middle Mile Driver with data below:
      | requestBody | {"username":"GENERATED","password":"{default-password}","first_name":"GENERATED","last_name":"GENERATED","license_number":"GENERATED","license_type":"Class 3A","driver_type":"Middle-Mile-Driver","license_expiry_date":"{date: 3 days next, yyyy-MM-dd}","contact":{"active":true,"details":"{default-phone}","type":"Mobile Phone"},"contacts":[{"active":true,"details":"{default-phone}","type":"Mobile Phone"}],"employment_type":"In-House - Full-Time","employment_start_date":"{date: 0 seconds next, yyyy-MM-dd}","employment_end_date":"{date: 3 days next, yyyy-MM-dd}","hub_id":"{hub-id}","comments":"Generated by Common-MM","availability":true} |
    When API MM - Create "LAND_HAUL" Movement Schedule from "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}" with data below:
      | startTime | {date: 10 minutes next, yyyy-MM-dd HH:mm:ss} |
      | duration  | 00:00:10                                     |
      | drivers   | KEY_MM_LIST_OF_CREATED_MIDDLE_MILE_DRIVERS   |
    Given API Order - Shipper create multiple V4 orders using data below:
      | shipperClientId     | {shipper-v4-client-id}                                                                                                                                                                                                                                                                                                          |
      | shipperClientSecret | {shipper-v4-client-secret}                                                                                                                                                                                                                                                                                                      |
      | generateFromAndTo   | RANDOM                                                                                                                                                                                                                                                                                                                          |
      | v4OrderRequest      | { "service_type":"Return", "service_level":"Standard", "parcel_job":{ "is_pickup_required":true, "pickup_date":"{{next-1-day-yyyy-MM-dd}}", "pickup_timeslot":{ "start_time":"12:00", "end_time":"15:00"}, "delivery_start_date":"{{next-1-day-yyyy-MM-dd}}", "delivery_timeslot":{ "start_time":"09:00", "end_time":"22:00"}}} |
    Given API MM - Operator creates multiple 2 new shipments with type "LAND_HAUL" from hub id "{KEY_SORT_LIST_OF_CREATED_HUBS[1].id}" to "{KEY_SORT_LIST_OF_CREATED_HUBS[2].id}"
    Given API Sort - Operator adds order to shipment:
      | shipmentId | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id}                                                                                                        |
      | request    | {"order_country":"sg","tracking_id":"{KEY_LIST_OF_CREATED_TRACKING_IDS[1]}","hub_id":{KEY_SORT_LIST_OF_CREATED_HUBS[1].id},"action_type":"ADD"} |
    Given API MM - Operator closes shipments "KEY_MM_LIST_OF_CREATED_SHIPMENTS"
    Given API MM - Operator scan inbound single shipment to movement trip "KEY_MM_LIST_OF_CREATED_MOVEMENT_TRIPS[1]":
      | scanValue  | {KEY_MM_LIST_OF_CREATED_SHIPMENTS[1].id} |
      | scanType   | SHIPMENT_VAN_INBOUND                     |
      | actionType | ADD                                      |
    Given Operator go to menu Inter-Hub -> Movement Trips
    And Operator refresh page
    And Operator verifies movement Trip page is loaded
    And Operator sets movement trips filter with data below:
      | tab       | Departure                               |
      | originHub | {KEY_SORT_LIST_OF_CREATED_HUBS[1].name} |
    And Operator clicks on Load Trip Button
    And Operator verify Load Trip Button is gone
    When Operator clicks on "view" icon on the action column
    Then Operator verifies that the new tab with trip details is opened
    When Operator goes to current page plus parameters "?last_id=0&limit=100"
    And Operator goes to current page plus parameters "?last_id=803313&limit=100"
    When Operator click on Shipment tab
    Then Operator verifies the elements on Shipment tab are correct

  @KillBrowser @ShouldAlwaysRun
  Scenario: Kill Browser
    Given no-op
